CREATE TABLE tbl_books(

    B_CODE	VARCHAR2(20)		PRIMARY KEY,
    B_NAME	nVARCHAR2(125)	NOT NULL,	
    B_AUTHER	nVARCHAR2(125)	NOT NULL,
    B_COMP	nVARCHAR2(125),		
    B_YEAR	VARCHAR2(10),		
    B_IPRICE	NUMBER		
);



CREATE TABLE tbl_member (
    M_ID	VARCHAR2(20) PRIMARY KEY,
    M_PASSWORD	nVARCHAR2(125)	NOT NULL,	
    M_LOGIN_DATE	nVARCHAR2(10),		
    M_REM	nVARCHAR2(125)		
);

DROP TABLE tbl_member;

CREATE TABLE tbl_read_book(
    RB_SEQ	NUMBER PRIMARY KEY,
    RB_BCODE	VARCHAR2(20)	NOT NULL,	
    RB_DATE	VARCHAR2(10)	NOT NULL,	
    RB_STIME	VARCHAR2(10),		
    RB_RTIME	NUMBER(10,3),		
    RB_SUBJECT	nVARCHAR2(20),		
    RB_TEXT	nVARCHAR2(400)	,	
    RB_STAR	NUMBER		
);

insert into tbl_read_book(READ_SEQ.NEXTVAL, RB_CODE, RB_)
values();

CREATE SEQUENCE READ_SEQ
START WITH 1 INCREMENT BY 1;

DROP TABLE tbl_read_book;

ALTER TABLE tbl_read_book
ADD CONSTRAINT FK_READ_BOOKS
FOREIGN KEY (RB_BCODE)
REFERENCES tbl_books(B_CODE);
