CREATE TABLE tbl_users (

    U_ID	VARCHAR2(125) PRIMARY KEY,
    U_HNAME	NVARCHAR2(50) NOT NULL,
    U_PASSWORD	VARCHAR2(125) NOT NULL,
    U_PNAME	VARCHAR2(50) NOT NULL,
    U_PAGE VARCHAR2(50) NOT NULL,
    U_PWEIGHT VARCHAR2(125) NOT NULL

);

CREATE TABLE tbl_hospitals (

    H_SEQ VARCHAR2(125) PRIMARY KEY,
    H_NAME	NVARCHAR2(50),
    H_TEL	VARCHAR2(125),
    H_ADDR	VARCHAR2(50),
    H_PRICE VARCHAR2(50),
    U_ECTPET VARCHAR2(125)

);