CREATE TABLE tbl_books(

    B_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
    B_NAME	nVARCHAR2(125)	NOT NULL,	
    B_AUTHER	nVARCHAR2(125)	NOT NULL,	
    B_COMP	nVARCHAR2(125),		
    B_YEAR	NUMBER	NOT NULL,	
    B_IPRICE	NUMBER,		
    B_RPRICE	NUMBER	NOT NULL	
    
);

CREATE TABLE tbl_users(

    U_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
    U_NAME	nVARCHAR2(125)	NOT NULL,	
    U_TEL	nVARCHAR2(125),		
    U_ADDR	nVARCHAR2(125)		

);

CREATE TABLE tbl_rent_book(

    RENT_SEQ	NUMBER	PRIMARY KEY,	
    RENT_DATE	VARCHAR2(10)	NOT NULL,	
    RENT_RETURN_DATE	VARCHAR2(10)	NOT NULL,
    RENT_BCODE	VARCHAR2(6)	NOT NULL,	
    RENT_UCODE	VARCHAR2(6)	NOT NULL,	
    RENT_RETUR_YN	VARCHAR2(1),		
    RENT_POINT	NUMBER DEFAULT 0	
    
);

DROP TABLE tbl_rent_book;

DESC tbl_rent_book;

CREATE SEQUENCE SEQ_BOOKS
START WITH 1 INCREMENT BY 1;

INSERT INTO tbl_rent_book(rent_seq)
VALUES(SEQ_BOOKS.NEXTVAL);

ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_USER 
FOREIGN KEY(rent_ucode)
REFERENCES tbl_users(u_code);

ALTER TABLE tbl_rent_book
ADD CONSTRAINT FK_BOOK
FOREIGN KEY (rent_bcode)
REFERENCES tbl_books(b_code);
