-- 관리자화면
CREATE TABLESPACE ioList2_DB
DATAFILE '/bizwork/oracle/data/iolist2.dbf'
SIZE 10M AUTOEXTEND ON NEXT 100K;

CREATE USER iolist2 IDENTIFIED BY iolist2
DEFAULT TABLESPACE iolist2_db;

GRANT DBA TO iolist2;